### ISSUE TITLE
(GUI) Member - check out book(s)

### ISSUE THREAD

**Issue by AdamHerbst** [AdamHerbst/LibrarySystem#7]
As a user with a library card I want to be able to check out books using my library card.

Tasks: By the end of this sprint, a user must be able to check out books using their library card. The book can be reserved using their username or their user_id. Once this book is checked out, it will show up in the database as checked out (their will be next to it).

A user will check out books through their "User View" page. The "User View" page looks similar to the "Librarian View". 

Below is the User View:
![image](https://user-images.githubusercontent.com/60015202/77872962-8dad1900-7216-11ea-86e0-95f3be4c7cb6.png).

When the user selects a book then clicks the "Check Out" button, the book should disappear from table and should be moved to a table that will only be visible after the user clicks the "My Books" button. 
![image](https://user-images.githubusercontent.com/60015202/77873044-cbaa3d00-7216-11ea-9538-5301538435ac.png).

The table visible when the "My Books" button is clicked will have 2 additional fields, "Issued date" and "returned date". 

Time Estimation: This functionality will be executed during the fourth sprint cycle (EI #4).

**Comment by mauleenn** [comment]
This functionality is incomplete and will not be included in the system.
